1) Generate an array of zeroes using inbuilt numpy function.¶

In [2]:
import numpy as np
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2) Run the given code and find the dot product of both arrays.

In [1]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[3 5 6 9]
 [2 8 4 8]
 [8 4 3 9]]
[[8 9 8]
 [7 5 2]
 [5 3 3]
 [8 4 9]]


In [2]:
a.dot(b)

array([[161, 106, 133],
       [156, 102, 116],
       [179, 137, 162]])

In [3]:
b.dot(a)

array([[106, 144, 108, 216],
       [ 47,  83,  68, 121],
       [ 45,  61,  51,  96],
       [104, 108,  91, 185]])

3)Read the csv file provided using pandas and display the first 5 entries¶


In [4]:
import pandas as pd
df =pd.read_csv('/content/data.csv')
df

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                      Fort Ransom State Park  ...   0.000444   0.128733
4         25                   Grahams Island State Park  ...   0.000469   0.125546
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
8         29         Lewis and Clark Interpretive Center  ...   0.000007   0.016774
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
10        31                  Little Missouri State Park  ...   0.003136   0.313756
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357

[25 rows x 6 columns]

In [5]:
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

4)Describe the data with all features.

In [6]:
df.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800


5)Find the total count of missing values for each feature.


In [7]:
df.isna ().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

6)Display all the unique values from the 'DESCRIPTION’ column.¶

In [8]:
df.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [9]:
df.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

8)Generate a random sample of 10 rows from the data.¶

In [10]:
df.sample(n=10)

OBJECTID                              UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
9         30      Fort Mandan State Recreation Area  ...   0.000005   0.009396
22        44  Turtle Mountain State Recreation Area  ...   0.000345   0.086487
13        36  Crow Flies High State Recreation Area  ...   0.000120   0.050518
1         22                 Beaver Lake State Park  ...   0.000129   0.080067
14        33                Turtle River State Park  ...   0.000378   0.145220
6         27              Lake Metigoshe State Park  ...   0.000751   0.212196
24        42    Pelican Point State Recreation Area  ...   0.000013   0.026357
8         29    Lewis and Clark Interpretive Center  ...   0.000007   0.016774
17        38    Fahlgren Park State Recreation Area  ...   0.000010   0.013294
15        34              Lake Sakakawea State Park  ...   0.000357   0.191806

[10 rows x 6 columns]

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [11]:
df = df.assign(New_feature = np.random.random())

print(df)

    OBJECTID  ... New_feature
0         21  ...     0.95642
1         22  ...     0.95642
2         23  ...     0.95642
3         24  ...     0.95642
4         25  ...     0.95642
5         26  ...     0.95642
6         27  ...     0.95642
7         28  ...     0.95642
8         29  ...     0.95642
9         30  ...     0.95642
10        31  ...     0.95642
11        32  ...     0.95642
12        35  ...     0.95642
13        36  ...     0.95642
14        33  ...     0.95642
15        34  ...     0.95642
16        37  ...     0.95642
17        38  ...     0.95642
18        39  ...     0.95642
19        40  ...     0.95642
20        41  ...     0.95642
21        43  ...     0.95642
22        44  ...     0.95642
23        45  ...     0.95642
24        42  ...     0.95642

[25 rows x 7 columns]


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
 6   New_feature  25 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.5+ KB


10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [13]:
print(df['OBJECTID'].mean())

33.0


In [16]:
df['OBJECTID'] = df['OBJECTID'].replace(33,0)


In [17]:

df.OBJECTID

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14     0
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64